### ISSUE TITLE
ReferenceError: jsx is not defined

### ISSUE THREAD

**Issue by craftzdog** [elpnt/inkdrop-chartjs#15]
Hi Elpnt!

I've got a bug report on the user forum here: https://forum.inkdrop.app/t/error-when-using-two-extensions-chartjs-and-markmap/3753/3
It seems that the error happens in the library react-resize-aware:

<img width="571" alt="CleanShot 2023-02-06 at 08 58 18@2x" src="https://user-images.githubusercontent.com/1332805/216853471-b75c73fb-62e2-4433-ac2d-5a8a4a503e13.png">

Could you look into it?

**Comment by elpnt** [comment]
Thanks for the report!

I replaced `react-resize-aware` with `react-resize-detector` and confirmed it worked well.

**Comment by craftzdog** [comment]
Confirmed it's been solved! Thank you🙏
